cleanups

diff --git a/mxcolr b/mxcolr
--- a/mxcolr
+++ b/mxcolr
@@ -15,7 +15,12 @@ O_SEED=$MXDIST/seed.mx
 if ! command -v pastel &> /dev/null; then
   echo "pastel not found."; echo " ==> https://github.com/sharkdp/pastel#installation"; exit 1
 fi
-if ! command -v jq &> /dev/null; then echo "jq not found."; echo " ==> https://github.com/stedolan/jq"; exit 1; fi
+if ! command -v jq &> /dev/null; then
+  echo "jq not found."; echo " ==> https://github.com/stedolan/jq"; exit 1
+fi
+if ! command -v bc &> /dev/null; then
+  echo "GNU bc not found."; echo " ==> https://www.gnu.org/software/bc"; exit 1
+fi
 
 if [ -d "$MXLIB" ]; then . "$MXLIB"/lib.mxtrap.sh; else mlg () { echo "${FUNCNAME[1]}:${BASH_LINENO[1]} => ${*}" >> /tmp/mxsh.log; }; fi
 
